using System;
using System.Linq;
using System.Net.Mail;
using System.Text;

namespace E_door_System.Models
{
    public class mailHelper
    {
        /// <summary>
        /// 发邮件
        /// </summary>
        /// <param name="cont">内容</param>
        /// <param name="mail_to">收件人地址</param>
        /// <param name="mail_cc">抄送收件人地址</param>
        /// <param name="mailSubject">邮件主题</param>
        /// <returns></returns>
        /// 
        public static bool SendEmail(string mailfrom, string mail_to, string mail_cc, string mailSubject, string cont)
        {
            /********************jabil******************/
            string smtpServer = "CORIMC04"; //SMTP服务器
            string mailFrom = "E_Door@jabil.com"; //登陆用户名
            string url = "http://www.baidu.com";//网页发布得到位置
            // 邮件服务设置
            SmtpClient smtpClient = new SmtpClient();
            smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;//指定电子邮件发送方式
            smtpClient.Host = smtpServer; //指定SMTP服务器
            smtpClient.EnableSsl = false;//import
            smtpClient.Port = 25;
            // 发送邮件设置        
            MailMessage mailMessage = new MailMessage(); // 发送人
            mailMessage.From = new MailAddress(mailFrom);
            mailMessage.To.Add(mail_to);//收件人
           
            mailMessage.Subject = mailSubject;//主题     
            mailMessage.Body += "你的e-door项目有了新的变更</br>There have some changes in you e-Door project </br></br>";
            mailMessage.Body += cont;
            mailMessage.Body += "</br></br></br>";
            mailMessage.Body += "请点击下面链接进行操作</br>Please click following url into the system.";
            mailMessage.Body += "<br/><br/>";
            mailMessage.Body += url;
            mailMessage.Body += "<br/><br/>";
            mailMessage.Body += "这是一封系统邮件，请勿直接回复！<br/>" +
                "This email is generated by system automatically, please do not reply directly!<br/>";
            mailMessage.BodyEncoding = Encoding.UTF8;//正文编码       
            mailMessage.IsBodyHtml = true;//设置为HTML格式
            mailMessage.Priority = MailPriority.Low;//优先级
            try
            {
                smtpClient.Send(mailMessage); // 发送邮件
                mailMessage.Dispose();
                smtpClient.Dispose();
                return true;
            }
            catch (SmtpException ex)
            {
                return false;
            }
        }
    }
}